name: Detect Objects on Camera modified
description: This example showcases object detection within a live feed from a USB camera.
ports: []

dependencies:
  python:
    - paho-mqtt
    - opencv-python
    - numpy
    - python-socketio[client]
    - pytz

bricks:
- arduino:video_object_detection: {}
- arduino:web_ui: {}
icon: 📽️
