name: detect-objects-on-camera-modified
include:
- /home/arduino/.local/share/arduino-app-cli/assets/0.5.0/compose/arduino/video_object_detection/brick_compose.yaml
services:
  main:
    image: ghcr.io/arduino/app-bricks/python-apps-base:0.5.0
    depends_on:
      ei-video-obj-detection-runner:
        condition: service_healthy
    volumes:
    - type: bind
      source: /home/arduino/ArduinoApps/detect-objects-on-camera-modified
      target: /app
    - type: bind
      source: /var/run/arduino-router.sock
      target: /var/run/arduino-router.sock
    - type: bind
      source: /dev/v4l
      target: /dev/v4l
    - type: bind
      source: /sys/class/leds/blue:user
      target: /sys/class/leds/blue:user
    - type: bind
      source: /sys/class/leds/green:user
      target: /sys/class/leds/green:user
    - type: bind
      source: /sys/class/leds/red:user
      target: /sys/class/leds/red:user
    - type: bind
      source: /sys/class/leds/blue:bt
      target: /sys/class/leds/blue:bt
    - type: bind
      source: /sys/class/leds/green:wlan
      target: /sys/class/leds/green:wlan
    - type: bind
      source: /sys/class/leds/red:panic
      target: /sys/class/leds/red:panic
    devices:
    - /dev/video0
    - /dev/video1
    - /dev/video2
    - /dev/video3
    - /dev/snd
    - /dev/dri
    ports:
    - 7000:7000
    user: 1000:1000
    group_add:
    - dialout
    - video
    - audio
    - render
    - gpiod
    entrypoint: /run.sh
    extra_hosts:
    - msgpack-rpc-router:host-gateway
    labels:
      cc.arduino.app: "true"
      cc.arduino.app.main: "true"
      cc.arduino.app.path: /home/arduino/ArduinoApps/detect-objects-on-camera-modified
    environment:
      APP_HOME: /home/arduino/ArduinoApps/detect-objects-on-camera-modified
      CUSTOM_MODEL_PATH: /home/arduino/.arduino-bricks/ei-models/
      EI_OBJ_DETECTION_MODEL: /models/ootb/ei/yolo-x-nano.eim
      HOST_IP: 192.168.30.223
      VIDEO_DEVICE: /dev/video0
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 5m
